#Minecraft server properties
#Please do not change server IP and port, even if you change its 

gamemode=survival
enable-command-block=true
level-name=Sami Logam
motd=\u00A7b\u00A7b\u00A7lSami Logam Host\u00A7e\u00A7 slogam.us.to\u00A7d\u00A7l Adarsh Official\u00A7r\u00A7r\n                \u00A7a\u00A7lR.I.P \u00A7c\u00A7lT\u00A7a\u00A7le\u00A7d\u00A7lc\u00A79\u00A7ln\u00A7f\u00A7lo\u00A74\u00A7lb\u00A72\u00A7ll\u00A71\u00A7la\u00A7a\u00A7ld\u00A7b\u00A7le
query.port=25565
pvp=true
difficulty=easy
network-compression-threshold=256
max-tick-time=60000
max-players=30

